# Generated by Django 3.2.9 on 2022-01-21 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='UserId',
        ),
    ]
