# Generated by Django 3.2.9 on 2022-01-21 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_rename_user_userid'),
    ]

    operations = [
        migrations.AddField(
            model_name='userid',
            name='username',
            field=models.CharField(default='', editable=False, max_length=1000000),
        ),
    ]
