# Generated by Django 3.2.9 on 2022-01-21 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_userid_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userid',
            name='username',
            field=models.CharField(default='', max_length=1000000),
        ),
    ]
