# Generated by Django 3.2.9 on 2022-01-21 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_auto_20220121_1829'),
    ]

    operations = [
        migrations.AddField(
            model_name='userid',
            name='id',
            field=models.BigAutoField(auto_created=True, default=2, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userid',
            name='userId',
            field=models.CharField(default=65347608, max_length=1000000),
        ),
    ]
