# Generated by Django 3.2.9 on 2022-01-24 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_userid_rooms'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='password',
            field=models.CharField(default='', max_length=1000000),
        ),
    ]
